Repository GoogleCloudPlatform/pbmm-on-gcp-onboarding, pull requests merged in 2024-04, with the labels that each got.

#352 352 - branch - Fortigate yopps- Added a fortigate module and docs for deploying fortigate.
  docs/fortigate.md
  docs/images/image1.png
  docs/images/image10.png
  docs/images/image11.png
  docs/images/image12.png
  docs/images/image13.png
  docs/images/image14.png
  docs/images/image15.png
  docs/images/image16.png
  docs/images/image17.png
  docs/images/image18.png
  docs/images/image2.png
  docs/images/image3.png
  docs/images/image4.png
  docs/images/image5.png
  docs/images/image6.png
  docs/images/image7.png
  docs/images/image8.png
  docs/images/image9.png
  modules/fortigate-appliance/README.md
  modules/fortigate-appliance/examples/cloud_nat.tf
  modules/fortigate-appliance/examples/locals.tf
  modules/fortigate-appliance/examples/main.tf
  modules/fortigate-appliance/examples/outputs.tf
  modules/fortigate-appliance/examples/test-only-firewall.tf
  modules/fortigate-appliance/examples/variables.tf
  modules/fortigate-appliance/files/FGVM08TM21002329.lic
  modules/fortigate-appliance/files/FGVM08TM21002330.lic
  modules/fortigate-appliance/files/lic1.lic
  modules/fortigate-appliance/files/lic2.lic
  modules/fortigate-appliance/firewallrule.tf
  modules/fortigate-appliance/loadbalance.tf
  modules/fortigate-appliance/locals.tf
  modules/fortigate-appliance/main.tf
  modules/fortigate-appliance/naming.tf
  modules/fortigate-appliance/outputs.tf
  modules/fortigate-appliance/route.tf
  modules/fortigate-appliance/templates.tf
  modules/fortigate-appliance/templates/metadata.tpl
  modules/fortigate-appliance/templates/replication.tpl
  modules/fortigate-appliance/variables.tf
Labels: fortigate

#363 #362 - bootstrap prereq
  0-bootstrap/README.md
Labels: tef

#369 #360 - 0-bootstrap/1-org to 5-app-infra readme changes
  0-bootstrap/README.md
  1-org/README.md
  2-environments/README.md
  3-networks-hub-and-spoke/README.md
  4-projects/README.md
  5-app-infra/README.md
  scripts/validate-requirements.sh
Labels: tef, tefv4+

#378 Architecture documentation - ongoing
  docs/architecture.md
Labels: tef
